version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/usr/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_HOST: database
  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  gem_cache:
  db_data:
  node_modules:
